### ISSUE TITLE
右侧目录超出页面时可以自动滚动吗

### ISSUE THREAD

**Issue by yyyyxzz** [yaowei9363/vue-side-catalog#2]
当右侧目录很长，超过页面高度时，可以自动将当前目录移动页面高度中心吗？
https://juejin.im/post/5eb3bac66fb9a043271c64e9
比如上面链接中右侧的目录很长，可以保持把当前目录位置在页面中心吗

**Comment by verymuch** [comment]
感谢反馈，当目录超长需要滚动时，可以支持当前目录保持在可视区域。我们尽快安排上

**Comment by yyyyxzz** [comment]
> 感谢反馈，当目录超长需要滚动时，可以支持当前目录保持在可视区域。我们尽快安排上

作者你好，使用过程中遇到了一个bug，可以邮箱联系一下吗，1601023075@qq.com

**Comment by yaowei9363** [comment]
你新开一个issues，按照模板提供复现问题的codesandbox地址，这样方便我快速找到问题

发自我的iPhone

**Comment by yaowei9363** [comment]
发布了v2.0.0 参数改动较大，目录超出滚动设定height就可以了，可以看下文档。
