### ISSUE TITLE
示例使用refList报错

### ISSUE THREAD

**Issue by yajun-L** [yaowei9363/vue-side-catalog#3]
在demo中修改成使用refList报错：
Error in mounted hook (Promise/async): "TypeError: Cannot read property '_isVue' of undefined"

子组件获取不到父组件的ref

**Comment by yaowei9363** [comment]
demo中需要解开一些注释，请看这个例子https://codesandbox.io/s/vue-side-catalogreflist-xxvnc?file=/src/App.vue

**Comment by yajun-L** [comment]
解决了，我用refList的时候用了slot里面的ref，所以报错了，谢谢
