### ISSUE TITLE
页面内容如果是通过v-html，无法加载侧边栏的问题

### ISSUE THREAD

**Issue by moxi624** [yaowei9363/vue-side-catalog#4]
您好，非常感谢你提供的目录侧边栏插件。但是我们使用的过程中遇到了问题，就是假设我的内容是通过v-html动态生成的，例如下面的样子
`
        <div
          class="news_con ck-content"
          v-html="blogData.content"
        >
`
那么我的目录无法显示，但是如果是静态的内容的话，是能够正常加载的

**Comment by yaowei9363** [comment]
可以参考[这个例子](https://codesandbox.io/s/vue-side-catalog4-eif5b?file=/src/App.vue)。
如果该例子不能解决你的问题，请在[该示例](https://codesandbox.io/s/vue-side-catalog-ynw1i?file=/src/App.vue)中fork一份，重现你的问题保存并反馈链接，谢谢！

**Comment by moxi624** [comment]
非常感谢您的回复，后面我通过你实例，添加了this.setTimeout，就能够成功渲染出来了，这是我加上您组件后的[效果](http://moguit.cn/#/info?blogUid=0762bfb392c2cf0a94c8a7934fe46f8f)，再次感谢您项目的支持~，

**Comment by yaowei9363** [comment]
> 非常感谢您的回复，后面我通过你实例，添加了this.setTimeout，就能够成功渲染出来了，这是我加上您组件后的[效果](http://moguit.cn/#/info?blogUid=0762bfb392c2cf0a94c8a7934fe46f8f)，再次感谢您项目的支持~，

例子中给setTimeout 只是模拟v-html的请求，并不是要用setTumeout来解决。另外我再你的[这篇文章](http://moguit.cn/#/info?blogUid=25ac64d4d11f62c0b3c9366346cf084c)中发现你是把源码下载下来了，为什么不用`npm install vue-side-catalog -D`安装组件呢？

**Comment by moxi624** [comment]
嗯，最开始是使用 `npm install vue-side-catalog -D` 进行安装的，然后后面出现了问题，就直接引入源码作为组件了。刚刚我又重新安装您说的排查了一下，可能是之前都是把请求数据放在了create的钩子函数中，从而造成无法操作dom节点生成侧边目录，后面我把数据请求放在mounted中后，能够正常显示了~。关于为何在create中使用setTimeout 有效，我觉得应该是该函数让dom重新渲染了
