### ISSUE TITLE
当页面的标题过多时，侧边栏无法展示全部的内容

### ISSUE THREAD

**Issue by moxi624** [yaowei9363/vue-side-catalog#5]
**Describe your problem or other（描述你的问题或其他）**
您好，我现在遇到一个问题就是，当页面的标题过多时，侧边栏无法展示全部的内容， [异常示例](http://www.moguit.cn/#/info?blogUid=68020f4cff4a2028253440b34c5e079b)

**The addresses of the codesandbox to reproduce the problem（复现问题的codesandbox地址）**
Fork the example and reproduce the problem（fork该示例，并重现问题）

[codesanbox地址](https://codesandbox.io/s/vue-side-catalog-yjgzj?file=/src/App.vue)

**Please complete the following information:**
 - Browser：Chrome
 - Version： 1.0.5

**Comment by yaowei9363** [comment]
这个和 #2 是一个问题，最近就会着手解决这个问题

**Comment by moxi624** [comment]
嗯，麻烦您了，刚刚我也看到了，然后我把问题重新复现了一下~

**Comment by yaowei9363** [comment]
发布了v2.0.0 参数改动较大，目录超出滚动设定height就可以了，可以看下文档。

**Comment by moxi624** [comment]
感谢支持，前阵子一直在忙，今天尝试升级了一下，但是动态渲染数据的时候，目录侧边栏生成好像又出现问题了，不知道是我写的有问题，还是怎么的，你可以看下这个 [样例](https://codesandbox.io/s/vue-side-catalogv2-5izqf?file=/src/App.vue)

**Comment by yaowei9363** [comment]
动态渲染需要使用`watch`参数，开启dom监听

**Comment by verymuch** [comment]
> 感谢支持，前阵子一直在忙，今天尝试升级了一下，但是动态渲染数据的时候，目录侧边栏生成好像又出现问题了，不知道是我写的有问题，还是怎么的，你可以看下这个 [样例](https://codesandbox.io/s/vue-side-catalogv2-5izqf?file=/src/App.vue)

我看了一下，和你的 `<sticky>` 组件有关系，这个组件由内容决定高度，目录的高度设置的是动态计算，所以高度就都是0了，其实目录是在的。可以设置一个固定的高度，后者改变 `<sticky>` 组件的策略
