### ISSUE TITLE
无法显示 目录

### ISSUE THREAD

**Issue by ChunKitAu** [yaowei9363/vue-side-catalog#7]
代码：
 
                    <div id="codeView" class="entry-content" v-highlight >
                        <div id="blog_content" v-html="blog.content">{{blog.content}}</div>
                        <side-catalog class="catalog" v-bind="catalogProps"></side-catalog>
                    </div>

    import SideCatalog from "vue-side-catalog";
    import "vue-side-catalog/lib/vue-side-catalog.css";

 data(){
            return{
                catalogProps:{
                    container: '#blog_content',
                    title: "Contents",
                    levelList: ["h1", "h2", "h3", "h4", "h5"],
                },
                id:"",
                showDonate: false,
                blog:"",
                comments: [],
                imgUrl:"",

            }
        },
components: {
            Banner,
            sectionTitle,
            SideCatalog,
        },

页面上就显示着Contents的标题
都按着文档上写了  不知道哪里有问题

**Comment by verymuch** [comment]
可以放一下DOM吗？辅助确认下问题

> 题外话：代码有一丢丢乱，以后可以 preview 预览下

**Comment by yaowei9363** [comment]
`v-html` 需要把`watch`置为`true`，可以具体看下文档。详情请看[这个例子](https://codesandbox.io/s/vue-side-catalogv2vhtml-4werg?file=/src/App.vue:27364-27379)

**Comment by ChunKitAu** [comment]
谢谢  现在可以了

**Comment by jackyfzh** [comment]
@ChunKitAu 大佬能否把成功的代码放一下呢，我也遇到了这个问题，死活不行。

**Comment by ChunKitAu** [comment]
@jackyfzh  
```
                <div class="toc" v-show="catalog_show">
                    <side-catalog class="catalog" v-bind="catalogProps">
                        <template #default="{level, isActive}">
                            <i :class="['line-style', isActive ? 'line-style--active' : '']"></i>
                        </template>
                    </side-catalog>
                </div>
```

```
data() {
            return {
                catalogProps: {
                    container: "#blog_content",
                    watch: true,
                    height: "calc(100% - 100px)",
                    levelList: ["h1", "h2", "h3", "h4", "h5"],
                    activeColor: '#FE9600',
                }
            }
        },
```

```
mounted() {
            var _this = this;
            _this.id = this.$route.params.id;
            setTimeout(() => {
                _this.getAticle();
                _this.getComment();
            }, 500);
            window.addEventListener('scroll', this.handleScroll)
        },
```
那个 mounted 加载数据时要设置TimeOut

**Comment by jackyfzh** [comment]
@ChunKitAu 已经解决了，谢谢大佬啦
